spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orderTopic-update:
          destination: orderTopic
          contentType: application/json
        orderTopic-new:
          destination: orderTopic
          contentType: application/json